Advanced_School/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('authentication/', include('App_login.urls')),
    path('home/', include('App_main.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_main/urls.py
from django.urls import path
from . import views

app_name = 'App_main'

urlpatterns = [
    path('admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),
    path('admin-dept-students/<str:pk>/<str:dept>/', views.admin_specific_dept_students, name='admin-dept-students'),
    path('admin-student-disable/<int:k>/', views.admin_student_disable, name='admin-student-disable'),
    path('admin-student-activate/<int:k>/', views.admin_student_activate, name='admin-student-activate'),
    path('admin-new-routine', views.admin_publish_routine, name='admin-new-routine'),
    path('admins-routine', views.admins_routine, name='admins-routine'),
    path('admin-delete-routine/<int:pk>/', views.admin_delete_routine, name='admin-delete-routine'),
    path('admin-new-notice/', views.admin_publish_notice, name='admin-new-notice'),
    path('admin-all-notices/', views.admin_all_notices, name='admin-all-notices'),
    path('admin-delete-notice/<int:pk>/', views.admin_delete_notice, name='admin-delete-notice'),
    path('admin-batch-based-attendance/', views.admin_batch_based_attendance, name='admin-batch-based-attendance'),
    path('admin-semester-attendance-delete/<str:semester>/<str:batch>/<str:department>/',
         views.admin_semester_attendance_delete,
         name='admin-semester-attendance-delete'),
    path('admin-student-attendance-record/', views.admin_student_attendance_record,
         name='admin-student-attendance-record'),
    path('admin-merit-list/', views.admin_test_results, name='admin-merit-list'),
    path('admin-delete-tests/<str:pk>/', views.admin_delete_tests, name='admin-delete-test'),
    path('admin-salary-distribution/', views.admin_salary_distribution, name='admin-salary-distribution'),
    path('admin-student-batch-dept/', views.student_batch_dept, name='admin-student-batch-dept'),
    path('admin-student-fees/<str:batch>/<str:dept>/', views.admin_student_fees, name='admin-student-fees'),
    path('admin-each-salary-record/<int:pk>/', views.admin_each_salary_record,
         name='admin-each-salary-record'),

    # admin end-----------------------------------------------------------------------------------------------
    # teacher start-----------------------------------------------------------------------------------------------
    path('teacher-dashboard/', views.teacher_dashboard, name='teacher-dashboard'),
    path('specific-department-students/<str:pk>/<str:dept>/', views.specific_dept_students,
         name='specific-dept-students'),
    path('student-disable/<int:k>/', views.student_disable, name='student-disable'),
    path('student-activate/<int:k>/', views.student_activate, name='student-activate'),
    path('new-assignment/', views.new_assignment, name='new-assignment'),
    path('assignment-submissions/', views.submitted_assignments, name='assignment-submissions'),
    path('delete-assignment/<str:pk>/', views.delete_assignments, name='delete-assignment'),
    path('assignment-marks/<int:pk>/', views.update_assignment_marks, name='update-assign-mark'),
    path('take-attendance/', views.take_attendance, name='take-attendance'),
    path('taking-attendance/<str:department>/<str:batch>/<str:section>/<str:semester>/<str:subject>/',
         views.taking_attendance, name='taking-attendance'),
    path('batch-based-attendance/', views.batch_based_attendance, name='batch-based-attendance'),
    path('student-attendance-record/', views.student_attendance_record, name='student-attendance-record'),
    path('semester-attendance-delete/<str:semester>/<str:batch>/<str:department>/', views.semester_attendance_delete,
         name='semester-attendance-delete'),
    path('take-exam/', views.take_exam, name='take-exam'),
    path('test-submissions/', views.submitted_test_papers, name='test-submissions'),
    path('delete-tests/<str:pk>/', views.delete_tests, name='delete-test'),
    path('test-marks/<int:pk>/', views.update_test_marks, name='update-test-mark'),
    path('merit-list/', views.test_results, name='merit-list'),
    path('new-routine', views.publish_routine, name='new-routine'),
    path('teachers-routine', views.teachers_routine, name='teachers-routine'),
    path('delete-routine/<int:pk>/', views.delete_routine, name='delete-routine'),
    path('new-notice/', views.publish_notice, name='new-notice'),
    path('teacher-all-notices/', views.teacher_all_notices, name='teacher-all-notices'),
    path('delete-notice/<int:pk>/', views.delete_notice, name='delete-notice'),

    # teacher end-----------------------------------------------------------------------------------------------
    # student start----------------------------------------------------------------------------------------------

    path('student-dashboard/', views.student_dashboard, name='student-dashboard'),
    path('submit-assignments/', views.submit_assignments, name='submit-assignments'),
    path('submit-file-assignment/<int:pk>/', views.update_assignment_file, name='submit-file-assignment'),
    path('assignment-marks/', views.submit_assignment_marks, name='assignment-marks'),
    path('student-attendance/', views.student_attendance, name='student-attendance'),
    path('student-routine/', views.students_routine, name='student-routine'),
    path('attend-exam/', views.attend_exam, name='attend-exam'),
    path('submit-test/<int:pk>/', views.submit_test, name='submit-test'),
    path('test-marks', views.test_marks, name='test-marks'),
    path('student-merit-list/', views.student_merit_list, name='student-merit-list'),
    path('student-all-notices/', views.student_all_notices, name='student-all-notices'),
    path('student-borrowed-books/', views.student_borrowed_books, name='student-borrowed-books'),
    path('student-borrow-records/', views.student_borrow_records, name='student-borrow-records'),
    path('student-monthly-fees/', views.student_monthly_fees, name='student-monthly-fees'),

    # Student end-----------------------------------------------------------------------------------------------
    # Accountant start----------------------------------------------------------------------------------------------

    path('accountant-dashboard/', views.accountant_dashboard, name='accountant-dashboard'),
    path('salary-list/', views.salary_list, name='salary-list'),
    path('salary-distribution/', views.salary_distribution, name='salary-distribution'),
    path('give-salary/<int:pk>/', views.provide_each_salary, name='give-salary'),
    path('student-fees/<str:batch>/<str:dept>/', views.student_fees, name='student-fees'),
    path('fee-approval/<int:pk>/', views.fee_approval, name='fee-approval'),
    path('accountant-all-notices/', views.accountant_all_notices, name='accountant-all-notices'),
    path('accountant-see-merit-list/', views.accountant_see_test_results, name='accountant-see-merit-list'),
    path('accountant-student-batch-dept/', views.accountant_student_batch_dept, name='accountant-student-batch-dept'),
    path('accountant-student-fees/<str:batch>/<str:dept>/', views.accountant_student_fees,
         name='accountant-student-fees'),
    path('accountant-each-salary-record/<int:pk>/', views.accountant_each_salary_record,
         name='accountant-each-salary-record'),

    # Accountant end-----------------------------------------------------------------------------------------------
    # Librarian start----------------------------------------------------------------------------------------------

    path('librarian-dashboard/', views.librarian_dashboard, name='librarian-dashboard'),
    path('book-category/', views.categories, name='book-category'),
    path('book-location/', views.locations, name='book-location'),
    path('all-book/', views.books, name='all-book'),
    path('cat-books/<str:cat>/', views.cat_books, name='cat-books'),
    path('delete-category/<int:pk>/', views.delete_category, name='delete-category'),
    path('delete-location/<int:pk>/', views.delete_location, name='delete-location'),
    path('delete-book/<int:pk>/', views.delete_book, name='delete-book'),
    path('book-details/<int:pk>/', views.book_view, name='book-details'),
    path('book-borrow/<int:pk>/', views.borrow, name='book-borrow'),
    path('book-return/<int:pk>/', views.return_book, name='book-return'),
    path('all-borrows/', views.all_borrows, name='all-borrows'),
    path('borrowed-books/', views.borrowed_books, name='borrowed-books'),
    path('librarian-all-notices/', views.librarian_all_notices, name='librarian-all-notices'),
    path('librarian-see-merit-list/', views.librarian_see_test_results, name='librarian-see-merit-list'),

    # Librarian end------------------------------------------------------------------------------------------------
    # Parent Start-----------------------------------------------------------------------------------------------
    path('parent-dashboard/', views.parent_dashboard, name='parent-dashboard'),
    path('parent-student-attendance-record/<int:pk>/', views.parent_student_attendance_record,
         name='parent-student-attendance-record'),
    path('parent-see-merit-list/', views.parent_see_test_results, name='parent-see-merit-list'),
    path('parent-borrowed-books/<int:pk>/', views.parent_borrowed_books, name='parent-borrowed-books'),
    path('parent-borrow-records/<int:pk>/', views.parent_borrow_records, name='parent-borrow-records'),
    path('parent-monthly-fees/<int:pk>/', views.parent_monthly_fees, name='parent-monthly-fees'),
    path('parent-all-notices/', views.parent_all_notices, name='parent-all-notices'),

    # Parent end-----------------------------------------------------------------------------------------------
    # Staff start-----------------------------------------------------------------------------------------------

    path('staff-dashboard/', views.staff_dashboard, name='staff-dashboard'),

templates/students/assignment_marks.html
{% extends 'students/student_base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Assignments Submissions
{% endblock %}

{% block style %}
    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }

        .table td,
        .table th {
            padding: 12px 15px;
        {#border: 1px solid #ddd;#} text-align: center;
            font-size: 16px;
        }

        .table th {
            color: #ffffff;
        }

        .table tbody tr {
            color: white;
        }

        /*responsive*/

        @media (max-width: 500px) {
            .table thead {
                display: none;
            }

            .table,
            .table tbody,
            .table tr,
            .table td {
                display: block;
                width: 100%;
            }

            .table tr {
                margin-bottom: 15px;
            }

            .table td {
                padding-left: 50%;
                text-align: left;
                position: relative;
            }

            .table td a {
                margin-left: auto;
                text-align: left;
                position: relative;
            }

            .table td::before {
                content: attr(data-label);
                position: absolute;
                left: 0;
                width: 50%;
                padding-left: 15px;
                font-size: 15px;
                font-weight: bold;
                text-align: left;
            }
        }

    </style>
{% endblock %}
{% block group_name %}
    Teacher
{% endblock %}

{% block body %}
    <article style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title_for_routine"><a href="" style="text-decoration: none; color: white"><b>Assignments</b></a>
                        </h1>
                    </div>
                </div>
            </div>
            {% for assignment in assignments %}
                <div class="row" style="margin: 1%">
                    <div class="neon__card">

                        <div class="container">
                            <table class="table" style="color: white;  height: fit-content;">
                                <h2 class="neon__title"
                                    style="text-align: center; color: white;margin-top: 5px;">{{ assignment|join:',' }} </h2>
                                <hr style="color: white">
                                <hr style="color: white">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Deadline</th>
                                    <th>Teacher</th>
                                    <th>Assignment</th>
                                    <th>Submission</th>
                                    <th>Submitted on</th>
                                    <th>Marks</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for submission in submissions %}
                                    {% if submission.my_assignment.Title == assignment|join:',' %}
                                        <tr>
                                            <td data-label="Deadline">{{ submission.my_assignment.deadline }}</td>
                                            <td data-label="Teacher">{{ submission.my_assignment.provider.first_name }} {{ submission.my_assignment.provider.last_name }}</td>
                                            <td data-label="Assignment"><a class="neon__button"
                                                                           style="color: white; height: 37px!important; width: fit-content!important; padding-top: 4%!important; margin-left: 20px!important;"
                                                                           href="http://
                                                                                   {{ request.META.HTTP_HOST }}{{ submission.my_assignment.assignment.url }}">Open File</a>
                                            </td>
                                            <td data-label="Submission"><a class="neon__button"
                                                                           style="color: white; height: 37px!important; width: fit-content!important; padding-top: 4%!important; margin-left: 20px!important;"
                                                                           href="http://
                                                                                   {{ request.META.HTTP_HOST }}{{ submission.submission_file.url }}">Open File</a>
                                            </td>
                                            <td data-label="Submitted on">{{ submission.created }}</td>
                                            <td data-label="Marks">{{ submission.marks }}</td>


                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>
            {% endfor %}
        </div>
    </article>


{% endblock %}

templates/students/attend_test.html
{% extends 'students/student_base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Tests
{% endblock %}

{% block style %}
    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }

        .table td,
        .table th {
            padding: 12px 15px;
        {#border: 1px solid #ddd;#} text-align: center;
            font-size: 16px;
        }

        .table th {
            color: #ffffff;
        }

        .table tbody tr {
            color: white;
        }

        /*responsive*/

        @media (max-width: 500px) {
            .table thead {
                display: none;
            }

            .table,
            .table tbody,
            .table tr,
            .table td {
                display: block;
                width: 100%;
            }

            .table tr {
                margin-bottom: 15px;
            }

            .table td {
                padding-left: 50%;
                text-align: left;
                position: relative;
            }

            .table td a {
                margin-left: auto;
                text-align: left;
                position: relative;
            }

            .table td::before {
                content: attr(data-label);
                position: absolute;
                left: 0;
                width: 50%;
                padding-left: 15px;
                font-size: 15px;
                font-weight: bold;
                text-align: left;
            }
        }

    </style>
{% endblock %}
{% block group_name %}
    Teacher
{% endblock %}

{% block body %}
    <article style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title_for_routine"><a href="" style="text-decoration: none; color: white"><b>Tests</b></a></h1>
                    </div>
                </div>
            </div>
            {% for test in tests %}
                <div class="row" style="margin: 1%">
                    <div class="neon__card">

                        <div class="container">
                            <table class="table" style="color: white;  height: fit-content;">
                                <h2 class="neon__title"
                                    style="text-align: center; color: white;margin-top: 5px;">{{ test|join:',' }} </h2>

                                <hr style="color: white">
                                <hr style="color: white">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Deadline</th>
                                    <th>Test Paper</th>
                                    <th>Add Answer Sheet</th>
                                    <th>Submit</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for submission in submissions %}
                                    {% if submission.my_test.Title == test|join:',' %}
                                        <tr>
                                            <td data-label="Deadline">{{ submission.my_test.deadline }}</td>
                                            <td data-label="Test Paper"><a class="neon__button"
                                                                               style="color: white; height: 37px!important; width: 100px!important; padding-top: 3%!important;"
                                            href="http://{{ request.META.HTTP_HOST }}{{ submission.my_test.test_paper.url }}">
                                                Open
                                            </a></td>


                                            <form method="post" enctype="multipart/form-data"
                                                  action="{% url 'App_main:submit-test' pk=submission.id %}">
                                                {% csrf_token %}
                                                <td data-label="Marks">
                                                    <input name="ans_file" type="file"
                                                           style="height: 30px; width: fit-content; border-radius: 25%; border: 2px solid #77778d; background-color: #020318; color: white">
                                                </td>
                                                <td>
                                                    <button type="submit" value="Submit" class="neon__button"
                                                            style="color: white; height: 37px!important; width: fit-content!important; padding-top: 0!important;">
                                                        <i class="fa fa-check" style="font-size:30px; color: white"></i>
                                                    </button>
                                                </td>
                                            </form>


                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>
            {% endfor %}
        </div>
    </article>


{% endblock %}

templates/students/dashboard.html
{% extends 'students/student_base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Student-Dashboard
{% endblock %}
{% block group_name %}
    Teacher
{% endblock %}
{% block body %}
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="" style="text-decoration: none; color: white"><img src="{{ profile.profile_picture.url }}" width="250px" height="300px"></a>
                    </div>
                </div>

                <div class="col-lg-8">
                    <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>---:---: {{ date }} :---:---</b></h1>
                    </div>
                </div>
            </div>
                    <div class="" style="margin: 5px; color: white">
                        <h1 class="neon__title_for_routine">
                            <b>{{ profile.user.first_name }} {{ profile.user.last_name }} - {{ profile.student_id }}</b></h1>
                        <hr>
                        <hr>
                        <div class="row">
                            <h1 style="font-size: 14px; float: left!important;">Department: {{ profile.department }}</h1>
                        </div>
                        <div class="row">
                            <h1 style="font-size: 14px; float: left!important;">Batch: {{ profile.batch }}</h1>
                        </div>
                        <div class="row">
                            <h1 style="font-size: 14px; float: left!important;">Section: {{ profile.section }}</h1>
                        </div>
                        <div class="row">
                            <h1 style="font-size: 14px; float: left!important;">Contact: {{ profile.phone_number }}</h1>
                        </div>
                        <div class="row">
                            <h1 style="font-size: 14px; float: left!important;">Email: {{ profile.user.email }}</h1>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>---:---:---: || Assignments || :---:---:---</b></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:submit-assignments' %}" style="color: white"><h3
                                class="neon__title_for_date">Submit Assignment</h3></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:assignment-marks' %}" style="color: white"><h3
                                class="neon__title_for_date">Assignment Marks</h3></a>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>---:---: || Attendance & Routines || :---:---</b></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-attendance' %}" style="color: white"><h3
                                class="neon__title_for_date">My Attendance</h3></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-routine' %}" style="color: white"><h3
                                class="neon__title_for_date">Routines</h3></a>
                    </div>
                </div>
            </div>

        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>---:---: || Library Records || :---:---</b></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-borrowed-books' %}" style="color: white"><h3
                                class="neon__title_for_date">Currently Borrowed Books</h3></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-borrow-records' %}" style="color: white"><h3
                                class="neon__title_for_date">Library Records</h3></a>
                    </div>
                </div>
            </div>

        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>-:|| Announcements and Information ||:-</b></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-all-notices' %}" style="color: white"><h3
                                class="neon__title_for_date">Announcements</h3></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-monthly-fees' %}" style="color: white"><h3
                                class="neon__title_for_date">Fees</h3></a>
                    </div>
                </div>
            </div>

        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>---:---:---:---:--- Class Tests ---:---:---:---:---</b></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:attend-exam' %}" style="color: white"><h3 class="neon__title_for_date">
                            Attend Exam</h3></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:test-marks' %}" style="color: white"><h3
                                class="neon__title_for_date">Obtained Marks</h3></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:student-merit-list' %}" style="color: white"><h3 class="neon__title_for_date">
                            Test Results</h3></a>
                    </div>
                </div>
            </div>
        </div>
    </article>


{% endblock %}