Advanced_School/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('authentication/', include('App_login.urls')),
    path('home/', include('App_main.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_main/urls.py
from django.urls import path
from . import views

app_name = 'App_main'

urlpatterns = [
    path('admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),
    path('admin-dept-students/<str:pk>/<str:dept>/', views.admin_specific_dept_students, name='admin-dept-students'),
    path('admin-student-disable/<int:k>/', views.admin_student_disable, name='admin-student-disable'),
    path('admin-student-activate/<int:k>/', views.admin_student_activate, name='admin-student-activate'),
    path('admin-new-routine', views.admin_publish_routine, name='admin-new-routine'),
    path('admins-routine', views.admins_routine, name='admins-routine'),
    path('admin-delete-routine/<int:pk>/', views.admin_delete_routine, name='admin-delete-routine'),
    path('admin-new-notice/', views.admin_publish_notice, name='admin-new-notice'),
    path('admin-all-notices/', views.admin_all_notices, name='admin-all-notices'),
    path('admin-delete-notice/<int:pk>/', views.admin_delete_notice, name='admin-delete-notice'),
    path('admin-batch-based-attendance/', views.admin_batch_based_attendance, name='admin-batch-based-attendance'),
    path('admin-semester-attendance-delete/<str:semester>/<str:batch>/<str:department>/',
         views.admin_semester_attendance_delete,
         name='admin-semester-attendance-delete'),
    path('admin-student-attendance-record/', views.admin_student_attendance_record,
         name='admin-student-attendance-record'),
    path('admin-merit-list/', views.admin_test_results, name='admin-merit-list'),
    path('admin-delete-tests/<str:pk>/', views.admin_delete_tests, name='admin-delete-test'),
    path('admin-salary-distribution/', views.admin_salary_distribution, name='admin-salary-distribution'),
    path('admin-student-batch-dept/', views.student_batch_dept, name='admin-student-batch-dept'),
    path('admin-student-fees/<str:batch>/<str:dept>/', views.admin_student_fees, name='admin-student-fees'),
    path('admin-each-salary-record/<int:pk>/', views.admin_each_salary_record,
         name='admin-each-salary-record'),

    # admin end-----------------------------------------------------------------------------------------------
    # teacher start-----------------------------------------------------------------------------------------------
    path('teacher-dashboard/', views.teacher_dashboard, name='teacher-dashboard'),
    path('specific-department-students/<str:pk>/<str:dept>/', views.specific_dept_students,
         name='specific-dept-students'),
    path('student-disable/<int:k>/', views.student_disable, name='student-disable'),
    path('student-activate/<int:k>/', views.student_activate, name='student-activate'),
    path('new-assignment/', views.new_assignment, name='new-assignment'),
    path('assignment-submissions/', views.submitted_assignments, name='assignment-submissions'),
    path('delete-assignment/<str:pk>/', views.delete_assignments, name='delete-assignment'),
    path('assignment-marks/<int:pk>/', views.update_assignment_marks, name='update-assign-mark'),
    path('take-attendance/', views.take_attendance, name='take-attendance'),
    path('taking-attendance/<str:department>/<str:batch>/<str:section>/<str:semester>/<str:subject>/',
         views.taking_attendance, name='taking-attendance'),
    path('batch-based-attendance/', views.batch_based_attendance, name='batch-based-attendance'),
    path('student-attendance-record/', views.student_attendance_record, name='student-attendance-record'),
    path('semester-attendance-delete/<str:semester>/<str:batch>/<str:department>/', views.semester_attendance_delete,
         name='semester-attendance-delete'),
    path('take-exam/', views.take_exam, name='take-exam'),
    path('test-submissions/', views.submitted_test_papers, name='test-submissions'),
    path('delete-tests/<str:pk>/', views.delete_tests, name='delete-test'),
    path('test-marks/<int:pk>/', views.update_test_marks, name='update-test-mark'),
    path('merit-list/', views.test_results, name='merit-list'),
    path('new-routine', views.publish_routine, name='new-routine'),
    path('teachers-routine', views.teachers_routine, name='teachers-routine'),
    path('delete-routine/<int:pk>/', views.delete_routine, name='delete-routine'),
    path('new-notice/', views.publish_notice, name='new-notice'),
    path('teacher-all-notices/', views.teacher_all_notices, name='teacher-all-notices'),
    path('delete-notice/<int:pk>/', views.delete_notice, name='delete-notice'),

    # teacher end-----------------------------------------------------------------------------------------------
    # student start----------------------------------------------------------------------------------------------

    path('student-dashboard/', views.student_dashboard, name='student-dashboard'),
    path('submit-assignments/', views.submit_assignments, name='submit-assignments'),
    path('submit-file-assignment/<int:pk>/', views.update_assignment_file, name='submit-file-assignment'),
    path('assignment-marks/', views.submit_assignment_marks, name='assignment-marks'),
    path('student-attendance/', views.student_attendance, name='student-attendance'),
    path('student-routine/', views.students_routine, name='student-routine'),
    path('attend-exam/', views.attend_exam, name='attend-exam'),
    path('submit-test/<int:pk>/', views.submit_test, name='submit-test'),
    path('test-marks', views.test_marks, name='test-marks'),
    path('student-merit-list/', views.student_merit_list, name='student-merit-list'),
    path('student-all-notices/', views.student_all_notices, name='student-all-notices'),
    path('student-borrowed-books/', views.student_borrowed_books, name='student-borrowed-books'),
    path('student-borrow-records/', views.student_borrow_records, name='student-borrow-records'),
    path('student-monthly-fees/', views.student_monthly_fees, name='student-monthly-fees'),

    # Student end-----------------------------------------------------------------------------------------------
    # Accountant start----------------------------------------------------------------------------------------------

    path('accountant-dashboard/', views.accountant_dashboard, name='accountant-dashboard'),
    path('salary-list/', views.salary_list, name='salary-list'),
    path('salary-distribution/', views.salary_distribution, name='salary-distribution'),
    path('give-salary/<int:pk>/', views.provide_each_salary, name='give-salary'),
    path('student-fees/<str:batch>/<str:dept>/', views.student_fees, name='student-fees'),
    path('fee-approval/<int:pk>/', views.fee_approval, name='fee-approval'),
    path('accountant-all-notices/', views.accountant_all_notices, name='accountant-all-notices'),
    path('accountant-see-merit-list/', views.accountant_see_test_results, name='accountant-see-merit-list'),
    path('accountant-student-batch-dept/', views.accountant_student_batch_dept, name='accountant-student-batch-dept'),
    path('accountant-student-fees/<str:batch>/<str:dept>/', views.accountant_student_fees,
         name='accountant-student-fees'),
    path('accountant-each-salary-record/<int:pk>/', views.accountant_each_salary_record,
         name='accountant-each-salary-record'),

    # Accountant end-----------------------------------------------------------------------------------------------
    # Librarian start----------------------------------------------------------------------------------------------

    path('librarian-dashboard/', views.librarian_dashboard, name='librarian-dashboard'),
    path('book-category/', views.categories, name='book-category'),
    path('book-location/', views.locations, name='book-location'),
    path('all-book/', views.books, name='all-book'),
    path('cat-books/<str:cat>/', views.cat_books, name='cat-books'),
    path('delete-category/<int:pk>/', views.delete_category, name='delete-category'),
    path('delete-location/<int:pk>/', views.delete_location, name='delete-location'),
    path('delete-book/<int:pk>/', views.delete_book, name='delete-book'),
    path('book-details/<int:pk>/', views.book_view, name='book-details'),
    path('book-borrow/<int:pk>/', views.borrow, name='book-borrow'),
    path('book-return/<int:pk>/', views.return_book, name='book-return'),
    path('all-borrows/', views.all_borrows, name='all-borrows'),
    path('borrowed-books/', views.borrowed_books, name='borrowed-books'),
    path('librarian-all-notices/', views.librarian_all_notices, name='librarian-all-notices'),
    path('librarian-see-merit-list/', views.librarian_see_test_results, name='librarian-see-merit-list'),

    # Librarian end------------------------------------------------------------------------------------------------
    # Parent Start-----------------------------------------------------------------------------------------------
    path('parent-dashboard/', views.parent_dashboard, name='parent-dashboard'),
    path('parent-student-attendance-record/<int:pk>/', views.parent_student_attendance_record,
         name='parent-student-attendance-record'),
    path('parent-see-merit-list/', views.parent_see_test_results, name='parent-see-merit-list'),
    path('parent-borrowed-books/<int:pk>/', views.parent_borrowed_books, name='parent-borrowed-books'),
    path('parent-borrow-records/<int:pk>/', views.parent_borrow_records, name='parent-borrow-records'),
    path('parent-monthly-fees/<int:pk>/', views.parent_monthly_fees, name='parent-monthly-fees'),
    path('parent-all-notices/', views.parent_all_notices, name='parent-all-notices'),

    # Parent end-----------------------------------------------------------------------------------------------
    # Staff start-----------------------------------------------------------------------------------------------

    path('staff-dashboard/', views.staff_dashboard, name='staff-dashboard'),

templates/librarians/book_details.html
{% extends 'librarians/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Book Details
{% endblock %}
{% block sec %}
    <section class="grid">
        <article
                style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px; padding-left: 20%!important;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="neon__card_for_month" style="margin: 5px">
                            <a href="" style="text-decoration: none; color: white"><img
                                    src="{{ book.cover.url }}" width="250px" height="300px"></a>
                        </div>
                    </div>

                    <div class="col-lg-8">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="neon__card_for_month" style="margin: 5px">
                                    <h1 class="neon__title"><b> {{ book.title }} </b></h1>
                                </div>
                            </div>
                        </div>
                        <div class="" style="margin: 5px; color: white;">
                            <h1 class="neon__title_for_routine">
                                <b>Author: {{ book.author }}</b><a href="{% url 'App_main:delete-book' pk=book.id %}"
                                                                   style="float: right">
                                <i class="fa fa-trash-o" style="font-size:30px; color: white"></i>
                            </a></h1>
                            <hr>
                            <hr>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Category: {{ book.categories }}</h1>
                            </div>
                            <hr>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Description: {{ book.description }}</h1>
                            </div>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Location: {{ book.location }}</h1>
                            </div>
                            <hr>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">Working
                                    Available: {{ book.available }}</h1>
                            </div>
                            <hr>
                        </div>
                    </div>
                </div>
                <hr style="color: white;">
                <div class="row" style="color: white;">
                    <form method="post" style="height: fit-content"
                          action="{% url 'App_main:book-borrow' pk=book.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-6">
                                    <label for="student-id" style="float: right" class="neon__title_for_routine">Issue
                                        this book to:</label>
                                </div>
                                <div class="col-lg-6">
                                    <input type="number" name="student_id" id="student-id" placeholder="Student Id"
                                           style="padding-left: 5px">
                                </div>
                            </div>
                        </div>

                        <div class="form-group" style="margin-top: 15px;">
                            <button type="submit" value="Submit" class="neon__button"
                                    style="color: white; height: 37px!important; width: 100%!important; padding-top: 0!important;">
                                <i class="fa fa-check" style="font-size:30px; color: white"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </article>
    </section>
{% endblock %}

{% block body %}
    <article style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row" style="margin: 1%">
                <div class="neon__card">
                    <div class="container">
                        <table class="table" style="color: white;  height: fit-content;">
                            <h2 class="neon__title"
                                style="text-align: center; color: white;margin-top: 5px;">Borrow Records</h2>
                            <hr style="color: white">
                            <hr style="color: white">
                            <thead class="thead-dark">
                            <tr>

                                <th>Student</th>
                                <th>Id</th>
                                <th>Quantity</th>
                                <th>Date</th>
                                <th>Status</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for borrow in borrows %}
                                <tr>
                                    <td data-label="Student">{{ borrow.user.student_id }}</td>
                                    <td data-label="Id">{{ borrow.user.user.first_name }} {{ borrow.user.user.last_name }}</td>
                                    <td data-label="Quantity">{{ borrow.quantity }}</td>
                                    <td data-label="Date">{{ borrow.date.day }}-{{ borrow.date|date:'F' }}-{{ borrow.date.year }}</td>
                                    {% if borrow.status %}
                                        <form method="post"
                                              action="{% url 'App_main:book-return' pk=borrow.id %}"
                                              style="margin-left: 100px!important;">
                                            {% csrf_token %}
                                            <td data-label="Grant">
                                                <button type="submit" value="Submit" class="neon__button"
                                                        style="color: white; height: 37px!important; width: 100%!important; padding-top: 0!important;">
                                                    Return
                                                </button>
                                            </td>
                                        </form>
                                    {% else %}
                                        <td data-label="Status">Returned</td>
                                    {% endif %}
                                </tr>
                                <hr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>


        </div>
    </article>
{% endblock %}

templates/librarians/category.html
{% extends 'librarians/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Book Categories
{% endblock %}

{% block style %}
    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }

        .table td,
        .table th {
            padding: 12px 15px;
        {#border: 1px solid #ddd;#} text-align: center;
            font-size: 16px;
        }

        .table th {
            color: #ffffff;
        }

        .table tbody tr {
            color: white;
        }

        /*responsive*/

        @media (max-width: 500px) {
            .table thead {
                display: none;
            }

            .table,
            .table tbody,
            .table tr,
            .table td {
                display: block;
                width: 100%;
            }

            .table tr {
                margin-bottom: 15px;
            }

            .table td {
                padding-left: 50%;
                text-align: left;
                position: relative;
            }

            .table td a {
                margin-left: auto;
                text-align: left;
                position: relative;
            }

            .table td::before {
                content: attr(data-label);
                position: absolute;
                left: 0;
                width: 50%;
                padding-left: 15px;
                font-size: 15px;
                font-weight: bold;
                text-align: left;
            }

        }

    </style>
{% endblock %}

{% block sec %}
    <article style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row" style="margin: 1%">
                <div class="neon__card" style="margin-left: 10%">
                    <h1 class="neon__title">Add new category</h1>
                    <hr>
                    <hr>
                    <div class="container">
                        <div class="container row">
                            <form method="post" name="new_cat">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <div class="form-group" style="margin-top: 15px;">
                                    <button type="submit" value="Submit" class="neon__button"
                                            style="color: white; height: 37px!important; width: 100%!important; padding-top: 0!important;">
                                        <i class="fa fa-check" style="font-size:30px; color: white"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>

{% endblock %}

{% block body %}
    <article style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row" style="margin: 1%">
                <div class="neon__card">
                    <div class="container">
                        <table class="table" style="color: white;  height: fit-content;">
                            <h2 class="neon__title"
                                style="text-align: center; color: white;margin-top: 5px;">All Categories</h2>
                            <hr style="color: white">
                            <hr style="color: white">
                            <thead class="thead-dark">
                            <tr>
                                <th>Index</th>
                                <th>Name</th>
                                <th>Quantity</th>
                                <th>Remove</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for cat, count in cat_count %}
                                <tr>
                                    <td data-label="Index"><a class="neon__button" style="color: white; height: 37px!important; width: 100%!important; padding-top: 0!important;" href="{% url 'App_main:cat-books' cat=cat.title %}">{{ forloop.counter }}.</a></td>
                                    <td data-label="Name">{{ cat.title }}</td>
                                    <td data-label="Quantity">{{ count }}</td>
                                    <form method="post" name="delete"
                                          action="{% url 'App_main:delete-category' pk=cat.id %}"
                                          style="margin-left: 100px!important;">
                                        {% csrf_token %}
                                        <td data-label="Remove">
                                            <button type="submit" value="Submit" class="neon__button"
                                                    style="color: white; height: 37px!important; width: 100%!important; padding-top: 0!important;">
                                                <i class="fa fa-trash-o" style="font-size:30px; color: white"></i>
                                            </button>
                                        </td>
                                    </form>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>


        </div>
    </article>


{% endblock %}

templates/librarians/dashboard.html
{% extends 'librarians/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block title %}
    Librarian-Dashboard
{% endblock %}
{% block sec %}
    <section class="grid">
        <article
                style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px; padding-left: 20%!important;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="neon__card_for_month" style="margin: 5px">
                            <a href="" style="text-decoration: none; color: white"><img
                                    src="{{ profile.profile_picture.url }}" width="250px" height="340px"></a>
                        </div>
                    </div>

                    <div class="col-lg-8">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="neon__card_for_month" style="margin: 5px">
                                    <h1 class="neon__title"><b> {{ date }} </b></h1>
                                </div>
                            </div>
                        </div>
                        <div class="" style="margin: 5px; color: white;">
                            <h1 class="neon__title_for_routine">
                                <b>{{ profile.user.first_name }} {{ profile.user.last_name }}</b></h1>
                            <hr>
                            <hr>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Address: {{ profile.address }}</h1>
                            </div>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Gender: {{ profile.gender }}</h1>
                            </div>
                            <hr>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Contact: {{ profile.phone_number }}</h1>
                            </div>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">
                                    Email: {{ profile.user.email }}</h1>
                            </div>
                            <hr>
                            <hr>
                            <div class="row">
                                <h1 style="font-size: 14px; float: left!important;">Working
                                    period: {{ profile.joining_date }} - Present</h1>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </article>
    </section>
{% endblock %}

{% block body %}
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <h1 class="neon__title"><b>---:---:---:---:---: || Books || :---:---:---:---:---</b></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:book-category' %}" style="color: white">
                            <h3 class="neon__title_for_date">Book Categories</h3>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:book-location' %}" style="color: white">
                            <h3 class="neon__title_for_date">Book locations</h3>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:all-book' %}" style="color: white">
                            <h3 class="neon__title_for_date">All Books</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </article>


    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:borrowed-books' %}" style="color: white">
                            <h3 class="neon__title_for_date">Borrowed Books</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:all-borrows' %}" style="color: white">
                            <h3 class="neon__title_for_date">Borrow Records</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <article
            style="background-color:#020318; height: fit-content!important; padding-bottom: 10px; padding-top: 10px">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="neon__card_for_month" style="margin: 5px">
                        <a href="{% url 'App_main:librarian-all-notices' %}" style="color: white"><h3 class="neon__title_for_date">
                            Announcements</h3></a>
                    </div>
                </div>
            </div>
        </div>
    </article>


{% endblock %}